"""
Debug why metric 22 has ticket_generated=1 but no ticket exists
"""
import sqlite3
import logging
from datetime import datetime

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

# Get metric 22's data
conn = sqlite3.connect('greenstack.db')
conn.row_factory = sqlite3.Row
cursor = conn.cursor()

cursor.execute("""
    SELECT m.*, a.file_type
    FROM pqa_quality_metrics m
    JOIN pqa_file_archive a ON m.archive_id = a.id
    WHERE m.id = 22
""")
row = cursor.fetchone()
metric = dict(row) if row else {}

if not metric:
    print("Metric 22 not found!")
    exit(1)

print(f"Metric 22:")
print(f"  Device ID: {metric.get('device_id')}")
print(f"  Score: {metric.get('overall_score'):.2f}%")
print(f"  ticket_generated: {metric.get('ticket_generated')}")
print(f"  Timestamp: {metric.get('analysis_timestamp')}")

# Get diff count
cursor.execute("SELECT COUNT(*) FROM pqa_diff_details WHERE metric_id = 22")
diff_count = cursor.fetchone()[0]
print(f"  Diff count: {diff_count}")

# Check if there are any tickets for device 1
cursor.execute("""
    SELECT COUNT(*) FROM tickets
    WHERE device_id = 1 AND category = 'parser_quality'
""")
ticket_count = cursor.fetchone()[0]
print(f"\nTickets for device 1 (parser_quality): {ticket_count}")

# Check if there are ANY tickets at all
cursor.execute("SELECT COUNT(*) FROM tickets")
total_tickets = cursor.fetchone()[0]
print(f"Total tickets in database: {total_tickets}")

# Get device name
cursor.execute("SELECT product_name FROM devices WHERE id = 1")
device_name = cursor.fetchone()[0]
print(f"\nDevice name: {device_name}")

# Now try to manually create a ticket like the code would have
print("\n" + "="*80)
print("Simulating ticket creation...")
print("="*80)

try:
    # Count existing tickets
    cursor.execute("SELECT COUNT(*) FROM tickets")
    ticket_count = cursor.fetchone()[0]
    ticket_number = f"TICKET-{str(ticket_count + 1).zfill(4)}"

    print(f"Ticket number: {ticket_number}")

    # Determine severity
    overall_score = metric['overall_score']
    critical_data_loss = metric['critical_data_loss']

    if critical_data_loss or overall_score < 80:
        severity = 'critical'
    elif overall_score < 90:
        severity = 'high'
    else:
        severity = 'medium'

    print(f"Severity: {severity}")

    description = f"""
## Parser Quality Analysis Results

**IODD File**: {device_name}
**Overall Score**: {overall_score:.1f}% ❌
**Data Loss**: {metric['data_loss_percentage']:.2f}%

### Score Breakdown
- Structural: {metric['structural_score']:.1f}%
- Attribute: {metric['attribute_score']:.1f}%
- Value: {metric['value_score']:.1f}%

*Auto-generated by PQA System* | Metric ID: 22
"""

    # Try INSERT
    print(f"\nAttempting INSERT with these values:")
    print(f"  ticket_number: {ticket_number}")
    print(f"  device_type: IODD")
    print(f"  device_id: 1")
    print(f"  title: Parser Quality Issue: {device_name} - Score {overall_score:.0f}%")
    print(f"  status: open")
    print(f"  priority: {severity}")
    print(f"  category: parser_quality")

    cursor.execute("""
        INSERT INTO tickets (
            ticket_number, device_type, title, description, status, priority, category,
            device_id, created_at, updated_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        ticket_number,
        'IODD',
        f"Parser Quality Issue: {device_name} - Score {overall_score:.0f}%",
        description,
        'open',
        severity,
        'parser_quality',
        1,
        datetime.now().isoformat(),
        datetime.now().isoformat()
    ))

    ticket_id = cursor.lastrowid
    print(f"\n✓ INSERT succeeded! Ticket ID: {ticket_id}")

    # Now update the metric
    print(f"\nUpdating metric 22 to set ticket_generated=1...")
    cursor.execute("""
        UPDATE pqa_quality_metrics
        SET ticket_generated = 1
        WHERE id = 22
    """)
    print(f"✓ UPDATE succeeded! Rows affected: {cursor.rowcount}")

    # Don't commit - this is just a test
    print(f"\nRolling back (test only)...")
    conn.rollback()
    print("✓ Rolled back")

except Exception as e:
    print(f"\n✗ Error: {e}")
    print(f"Error type: {type(e).__name__}")
    import traceback
    traceback.print_exc()
    conn.rollback()

finally:
    conn.close()
